# Configuración mínima — recibir logs remotos del lab (pfSense + Suricata)
module(load="imudp")
input(type="imudp" port="514")

module(load="imtcp")
input(type="imtcp" port="514")

$template labFormat,"%timestamp% %hostname% %syslogtag% %msg%\n"

if $fromhost-ip == '192.168.10.1' then {
    action(type="omfile" file="/var/log/pfsense.log" template="labFormat")
    stop
}

if $syslogtag contains 'suricata' or $msg contains 'Suricata' then {
    action(type="omfile" file="/var/log/suricata-remote.log" template="labFormat")
    stop
}

*.* action(type="omfile" file="/var/log/lab-all.log" template="labFormat")
